apiVersion: "kubean.io/v1alpha1"
kind: "Manifest"
metadata:
  name: "manifest-2-23-10679eb-demo"
spec:
  kubesprayVersion: "10679ebb5ded86187cdb6792c485e2fda25ff3e2"
  kubeanVersion: ""
  docker:
  - os: "redhat-7"
    defaultVersion: "20.10"
    versionRange:
    - "19.03"
    - "20.10"
  - os: "debian"
    defaultVersion: "20.10"
    versionRange:
    - "19.03"
    - "20.10"
  - os: "ubuntu"
    defaultVersion: "20.10"
    versionRange:
    - "19.03"
    - "20.10"
  components:
  - name: "cni"
    defaultVersion: "v1.3.0"
    versionRange:
    - "v1.3.0"
    - "v1.2.0"
  - name: "containerd"
    defaultVersion: "1.7.6"
    versionRange:
    - "1.7.6"
    - "1.7.5"
    - "1.7.4"
  - name: "kube"
    defaultVersion: "v1.27.5"
    versionRange:
    - "v1.26.6"
    - "v1.26.5"
    - "v1.26.4"
  - name: "calico"
    defaultVersion: "v3.26.1"
    versionRange:
    - "v3.26.1"
    - "v3.26.0"
    - "v3.25.2"
    - "v3.25.1"
  - name: "cilium"
    defaultVersion: "v1.13.4"
    versionRange: []
  - name: "flannel"
    versionRange: []
    defaultVersion: "v0.22.0"
  - name: "kube-ovn"
    versionRange: []
    defaultVersion: "v1.11.5"
  - name: "etcd"
    defaultVersion: "v3.5.9"
    versionRange:
    - "v3.5.9"
    - "v3.5.8"
